# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
vector=np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
memory=vector.nbytes
memory

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy as np; help(np.add)"


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
new = np.zeros(10)
new[4] = 1
new

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
rev = vec[::-1]
rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
index = np.nonzero(arr) 
index

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
t = np.random.random((3, 3, 3))
t

array([[[0.21616473, 0.03928183, 0.43711745],
        [0.99415067, 0.13189734, 0.35082796],
        [0.31030563, 0.6534648 , 0.60566107]],

       [[0.13022619, 0.8125355 , 0.53468211],
        [0.43262404, 0.54893105, 0.52423862],
        [0.46424903, 0.7822042 , 0.3343024 ]],

       [[0.60469189, 0.31560144, 0.22950202],
        [0.38177411, 0.77079907, 0.49227253],
        [0.70288859, 0.00115037, 0.78132118]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
arr = np.random.random((10, 10))
minn = arr.min()
maxx = arr.max()
print(minn, maxx)

0.008756337979063167 0.9955659516034846


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [40]:
vec = np.random.random(30)
mean = np.mean(vec)
print(mean)

0.44090719149558727


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [45]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [48]:
mat = np.diag([1, 2, 3, 4], k=-1)
mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [49]:
mat = np.zeros((8, 8), dtype=int)
mat[1::2, ::2] = 1
mat[::2, 1::2] = 1
mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [53]:
i = np.unravel_index(100,(6, 7, 8))
print(i)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [54]:
c = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
c

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [70]:
m = np.random.random((5, 5))
n = (m - np.min(m)) / (np.max(m) - np.min(m))
print(n)


# or 

from sklearn.preprocessing import StandardScaler
s=StandardScaler()
m=s.fit_transform(m)
print(m)

[[0.8799097  0.43362754 0.20904935 0.9691579  0.15363688]
 [0.56924556 0.78632328 0.93478969 0.70154591 0.73005327]
 [1.         0.28140826 0.59576565 0.65052899 0.29163848]
 [0.33202835 0.         0.54729397 0.07617731 0.2081146 ]
 [0.45472014 0.17952549 0.11893273 0.95482862 0.26898804]]
[[ 0.91839318  0.36692527 -0.92948943  0.92217208 -0.86049072]
 [-0.30754726  1.69491044  1.54947419  0.09600563  1.94416133]
 [ 1.39229259 -0.20621728  0.39144534 -0.06149279 -0.18902047]
 [-1.24365194 -1.26578776  0.22587713 -1.83461994 -0.5954201 ]
 [-0.75948657 -0.58983067 -1.23730724  0.87793502 -0.29923004]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [72]:
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
color_array

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [75]:
m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))
p = np.dot(m1, m2)
print(p)

[[0.28774025 0.15738445]
 [1.00810687 0.7161487 ]
 [0.50225842 0.83248573]
 [0.75455219 0.62665273]
 [1.04590534 0.6214833 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [82]:
a = np.arange(11)
a[(a > 3) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [87]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

"""
first -> 9
second -> 10
"""

10
10


'\nfirst -> 9\nsecond -> 10\n'

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [94]:
z=2

Z**Z          # Legal
#2 << Z >> 2   # illegal
#Z <- Z         # Illegal
1j*Z          # Legal
Z/1/1         # Legal
#Z<Z>Z         # Illegal

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [103]:
import warnings 
warnings.filterwarnings('ignore')

a=np.array(0)

#a/a       # nan

#a//a       # ZeroDivisionError

np.array([np.nan]).astype(int).astype(float)  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [110]:
a = np.random.uniform(-10,+10,10)

r = np.sign(a) * np.ceil(np.abs(a))

print(r)

[-6. -9. -2.  4. -7. -9. -1.  3.  9. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [111]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([3, 4, 5, 6])
c = np.intersect1d(a1, a2)

print(c)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [112]:
warnings.filterwarnings('ignore', 
                        category=RuntimeWarning, module='numpy')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [113]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [114]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print(yesterday, today, tomorrow)

2024-07-22 2024-07-23 2024-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [115]:
import pandas as pd

july_dates = pd.date_range(start='2016-07-01', end='2016-07-31', freq='D').date
july_dates

array([datetime.date(2016, 7, 1), datetime.date(2016, 7, 2),
       datetime.date(2016, 7, 3), datetime.date(2016, 7, 4),
       datetime.date(2016, 7, 5), datetime.date(2016, 7, 6),
       datetime.date(2016, 7, 7), datetime.date(2016, 7, 8),
       datetime.date(2016, 7, 9), datetime.date(2016, 7, 10),
       datetime.date(2016, 7, 11), datetime.date(2016, 7, 12),
       datetime.date(2016, 7, 13), datetime.date(2016, 7, 14),
       datetime.date(2016, 7, 15), datetime.date(2016, 7, 16),
       datetime.date(2016, 7, 17), datetime.date(2016, 7, 18),
       datetime.date(2016, 7, 19), datetime.date(2016, 7, 20),
       datetime.date(2016, 7, 21), datetime.date(2016, 7, 22),
       datetime.date(2016, 7, 23), datetime.date(2016, 7, 24),
       datetime.date(2016, 7, 25), datetime.date(2016, 7, 26),
       datetime.date(2016, 7, 27), datetime.date(2016, 7, 28),
       datetime.date(2016, 7, 29), datetime.date(2016, 7, 30),
       datetime.date(2016, 7, 31)], dtype=object)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [123]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

A += B
A*=-A/2

print(A)

[-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [127]:
a = np.random.random(5) * 10

a1 = np.floor(a)
a2 = np.trunc(a)
a3 = a.astype(int)
a4 = a // 1
print(a,a1,a2,a3,a4)

[4.02759283 2.71958642 4.99228552 8.67987239 3.02395398] [4. 2. 4. 8. 3.] [4. 2. 4. 8. 3.] [4 2 4 8 3] [4. 2. 4. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [130]:
mat = np.tile(np.arange(5), (5, 1))
mat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [131]:
def generate_integers():
    for i in range(10):
        yield i

array = np.array(list(generate_integers()))

array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [137]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [138]:
vec = np.random.random(10)
sort = np.sort(vec)
print(sort)

[0.2041607  0.34670225 0.40735257 0.41626885 0.42483186 0.50741113
 0.75077316 0.8828701  0.95878831 0.96871569]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [141]:
arr = np.array([1, 2, 3, 4, 5])
sum = arr.sum()
print(sum)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [144]:
A = np.random.random(10)
B = np.random.random(10)
e = np.array_equal(A, B)

print(e)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [146]:
arr = np.array([1, 2, 3, 4, 5])
arr.setflags(write=False)
print(arr)

[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [147]:
cartesian = np.random.random((10, 2))
x, y = cartesian[:, 0], cartesian[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar = np.column_stack((r, theta))

print(polar)

[[1.22403277 0.87784287]
 [0.95222877 0.53818502]
 [0.74576186 0.69855363]
 [1.13608993 0.52950695]
 [0.49517162 0.72747228]
 [0.57244385 0.26199401]
 [0.84346727 0.34244858]
 [0.99057104 0.96891222]
 [0.65445042 1.35342893]
 [1.28499062 0.88531959]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [152]:
vec = np.random.random(10)
vec[vec.argmax()] = 0

print(vec)

[0.56814033 0.07436526 0.36773608 0.16408371 0.52983251 0.45675634
 0.30294211 0.         0.45099458 0.32335864]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [153]:
arr = np.random.random(10)
np.set_printoptions(threshold=np.inf)
print(arr)

[0.8332299  0.42510517 0.13120417 0.62741271 0.91475956 0.7534989
 0.04308964 0.54288178 0.04297373 0.30331317]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [158]:
v = np.random.random(10)
s = 0.5
c = vector[np.abs(v - s).argmin()]
print(c)

0.295334040756991


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [162]:
arr = np.random.random(10).astype(np.float32)
arr = arr.astype(np.int32, copy=False)
print(arr.dtype)

int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [172]:
from io import StringIO


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)